### PR TITLE
Update sample network analysis notebook

### LINKED ISSUE #95: fix plot for hourly dispatch in sample_network_analysis notebook
As also mentioned in the [Youtube Tutorial #1](https://youtu.be/2nakM174CME?si=QLi5H6rlvw5Oq2aL), the stacked plot for hourly dispatch in the [sample_network_analysis notebook](https://github.com/pypsa-meets-earth/documentation/blob/fa259a8d108f9f6ae974afe675ce8842c41ba3fc/notebooks/sample_network_analysis.ipynb) has greater demand than generation. That's because:
- the power coming from the hydro-storage is not recognised
- the power from/ to the H2 and battery store is not separated for stacking positive/ negative numbers and just adds up with plt.stackplot.  
- when taking into account the H2 (and battery, which is not used in this scenario) store  itself:
  - H2.where(H2 > 0, 0),  : H2 discharging : p at H2 store is without loss, but grid supply is reduced behind link!    
  - H2.where(H2 < 0, 0), : H2 charging : power at H2 store reduced due to link (charging) efficiency, but grid withdrawal (before link) is higher!  
  - -> It would be clearer to show the direct withdrawal from / supply to the grid

When doing so, generation and demand areas are balanced (see the black withdrawal line)

The following updated code gives the diagram below (and additionally omits dealing with the color_map manually) :
```
...
hydro = n.storage_units_t.p.loc[first_date:second_date].T.groupby(n.storage_units.carrier).sum().loc['hydro']
H2_electrolysis = n.links_t.p0.loc[first_date:second_date].T.groupby(n.links.carrier).sum().loc['H2 electrolysis']*-1
H2_fuel_cell = n.links_t.p1.loc[first_date:second_date].T.groupby(n.links.carrier).sum().loc['H2 fuel cell']*-1
battery_charge = n.links_t.p0.loc[first_date:second_date].T.groupby(n.links.carrier).sum().loc['battery charger']*-1
battery_discharge = n.links_t.p1.loc[first_date:second_date].T.groupby(n.links.carrier).sum().loc['battery discharger']*-1

# names used for labels
demand.name = 'demand'
H2_electrolysis.name = "H2"
H2_fuel_cell.name = "H2"
battery_charge.name = 'battery'
battery_discharge.name = 'battery'

plt.stackplot(
    CCGT.index,
    supply:=(hydro.where(hydro > 0, 0), CCGT, OCGT, Onwind, battery_discharge, solar, H2_fuel_cell), 
    labels=[key.name for key in supply],
    colors=[n.carriers.color.get(source.name, default="gray") for source in supply], 
    zorder = 99
)

plt.stackplot(
    CCGT.index,
    withdrawal:=(demand, battery_charge, H2_electrolysis, hydro.where(hydro < 0, 0)),
    labels=[source.name for source in withdrawal],
    colors=[n.carriers.color.get(key.name, default="red") for key in withdrawal], 
    zorder = 1
)
plt.plot(sum(withdrawal).abs(), color = "black", label='abs(withdrawal)', linestyle='dashed', zorder=100)

handles, labels = ax.get_legend_handles_labels()
unique_labels = dict(zip(labels, handles))  # remove duplicates

....
```
image
  
Additionally, there are some minor issues with the notebook:
- `from _helpers import sets_path_to_root` is no longer available (and not needed) and raises an error
- `.groupby(n.generators.carrier, axis=1)` raises: `FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do frame.T.groupby(...) without axis instead.`.  This can be fixed with: `.T.groupby(n.storage_units.carrier).` in combination with .loc[...]
- `n.statistics._parent` raises an AttributeError for newer versions of pypsa (just printing n returns the same information)
(By the way: why is the pypsa version fixed to 0.24 in the environment.yaml for pypsa-earth, is there a specific reason?)

Maybe it would also be nice to add a link to the tutorial video mentioned above :)

Please let me know if I should open a PR.

### PR DESCRIPTION
**Pull request by mt7180**
With this PR the sample_network_analysis.ipynb notebook is updated.

Changes made:
- [x] fix plot for hourly dispatch in sample_network_analysis notebook (grid withdrawal and supply are balanced now)
- [x] add a link to the YouTube tutorial 
- [x] remove old import:  from _helpers import sets_path_to_root (raised an error)
- [x] resolve FutureWarning for .groupby() with axis=1  
- [x] replace n.statistics._parent with just printing n (raises an AttributeError for newer versions of pypsa)

Closes #95

### CODE REVIEW

**Comment by mt7180** [comment]
Hi @ekatef, just adding this comment to let you know that I opened the discussed PR. Just let me know if there is anything to change/improve :)

**Comment by ekatef** [comment]
> Hi @ekatef, just adding this comment to let you know that I opened the discussed PR. Just let me know if there is anything to change/improve :)

Hello @mt7180, thanks a lot for the contribution! That is indeed a very needed improvement, and I love the implementation you have developed for the dispatch plot.

I wonder if you could please re-run the notebook from a "clean" state to make sure that all the results are consistent? I see that you have used a more memory-saving approach which has allowed to avoid changing the fragments which haven't been changed by this PR. However, it has lead to some inconsistencies in numbering cells which could be probably misleading for beginner users. Does it make sense for you?

As a little technical comment, it would be great to ensure that we are using same quotes everywhere (that is relevant in particular for the fragment dealing with the dispatch plot). I recognise that it has been inherited from the original implementation, but if you would be willing to improve it, that would be much appreciated!

Otherwise, looks great and basically ready to merge 😄

**Comment by mt7180** [comment]
Hello @ekatef, of course, you're absolutely right!
Thank you for your kind review :)

Additional changes in sample_network_analysis notebook:
- made quotes consistent
- all notebook cells have been re-run from top to bottom

**Comment by ekatef** [comment]
> Hello @ekatef, of course, you're absolutely right! Thank you for your kind review :)
> 
> Additional changes in sample_network_analysis notebook:
> 
> * made quotes consistent
> * all notebook cells have been re-run from top to bottom

Awesome, thank you so much! Merged 😄 
Congratulations with getting done an amazing contribution! 🎉 🎉 🎉

**Pull request merged**
