### PR TITLE
Revise set current directory and fill notebooks

### PR DESCRIPTION
**Pull request by davide-f**
This PR is to revise the importing procedure of all notebooks to make it resilient with respect to the name of the parent directory.
All notebooks no more rely on set_to_root function to specify the parent folder

### CODE REVIEW

**Comment by davide-f** [comment]
I'll be merging this PR in the next days unless some comments appear

**Comment by ekatef** [comment]
@davide-f it feels like a huge relief when no usual path issues appear while going through the notebooks :)

The only small points could be added:
* `Paths` block in  `augmented_line_connections` seems to need some adjustments;
* in `validation_nigeria` names of the files could be updated in `Definition of main folder paths` (like `"africa_all_raw_substations.geojson"`)

**Comment by davide-f** [comment]
Nice catch! Revised both and tested :)

**Comment by davide-f** [comment]
Merging :) If little refuses are left (e.g. missing imports of some _helper functions) we may add them later when we discover them

**Pull request merged**
