### PR TITLE
Add notebook for make_statistics

### LINKED ISSUE #46: Add notebooks on `make_statistics`
See feature PR: https://github.com/pypsa-meets-earth/pypsa-earth/pull/579
Goal: describe how to use make statistics and what comes out of it

Notebook should include something like:
- instructions how to modify the config tutorial/ test case for Nigeria
- instructions what command to use to run the whole stats stuff
- some tables with the stats maybe with little explanations

(could make sense also for `run_all_scenarios`, `monte_carlo` stuff, `make_summary`, etc.)

### PR DESCRIPTION
**Pull request by javier-cp6**
Closes #46, closes pypsa-meets-earth/pypsa-earth#608 
Added a notebook that explains how to create statistics on the workflow by running the make_statistics rule.

### CODE REVIEW

**Comment by ekatef** [comment]
Hi @javier-cp6, your contribution is absolutely welcome! It would help a lot to have a demo on `make_stats`.

Adding to @pz-max suggestions regarding supplementing the values in the table with units, I think it would be great to play a bit around output formats, in particular:

1) keep a number of digits reasonable: currently our stats claims to know transmission lines length with nanometers precision with `clean_osm_data.3`;

2) find a way to deal with big numbers like those for `build_shapes`.

What do you think?

**Comment by javier-cp6** [comment]
Sure. I think I can also group the rules.

**Comment by davide-f** [comment]
Hello Javier :)
Many thanks for the PR and sorry for the delay but Max and Katia have covered the comments.
Personally, I really like the PR and I think little updates may be done to improve it.
In particular:
- note that the stats.csv is a dataframe that has a multi-index as columns. That is important and I am unsure that it is properly capture in the model.
  To read it you could use something like: `read_csv_nafix(str(stats_path), header=[0, 1], index_col=0)` using the read_csv_nafix from the helpers.
   Note that this is to prevent problems with namibia whose country code is "NA" and that may be interpreted as nan. If you don't want to import that function ok, but you shall use `pd.read_csv(..., na_values=["NULL"])`
- Agree with Max and Katia that for special inputs (e.g. population/ area etc), it may be worth adding some cells and some description to improve the quality of the analysis
- Other naming conventions, may be instead incorporated into make_statistics itself, e.g. if we prefer using `substations-no `instead of `substations-size` [not sure where those comments have moved to]

**Review by davide-f — COMMENTED** [review]
Beyond my previous comment, to run `make_statistics` the second point in the bullet list is not necessary

**Comment by javier-cp6** [comment]
Hi @pz-max @ekatef  @davide-f ,

Thanks for your hints. So far, I’ve updated the notebook with the following changes:

-	Replaced read_csv() with the read_csv_nafix() method from the helpers module to read the stats.csv file as a multi-index dataframe and prevent problems in case of a scenario where Namibia is present. 
-	Updated format of numbers (integers and floats) and keep transmission lines length with nine decimal places.
-	Added a new index column for units.

I need some help with the units for the stats. The rule does not generate them, so I'm looking in the make_statistics script and the resources folder generated for NG. However, I still need to complete the units for the remaining fields. Once I have completed this task, I will update the naming accordingly and add some cell descriptions.

**Comment by ekatef** [comment]
Hi @javier-cp6, a very nice work!
Sorry for a delay with the answer: a problem of chained deadlines 🙂 

My general feeling is the output looks much more clear now.  

It seems `lines_length` for some reasons keeps nine decimal points. Could you please check it?

Regarding adding the units, I'd be happy to help. Agree, that in some cases in could be currently a bit tricky to dig-out the dimensions from the code and docs :) So, investigation on that and adding units to the outputs is definitely worth efforts. Could you please give some updates on which parameters do you need help to find their units?

**Comment by javier-cp6** [comment]
Hi @ekatef ,
Thanks for your response. I've updated the notebook adding more units and descriptions. I've also fixed the `lines_length` format. 
I'll keep searching for the rest of units, could you please help me with `add_electricty` stats such as `OCGT` and `CCGT`?

**Comment by javier-cp6** [comment]
Hi @ekatef ,
Thanks! Almost done!  Indeed, installed capacity of generators is in MW, I think it is not necessary to explain CCGT and OCGT.  I've also added the units for `lines_capacity` (MVA), `potential` (MW), and `avg_production_pu` (MWh), and incorporated links to PyPSA documentation explaining those units. 

I still need to complete the following. Please let me know, if you have any hints:
- Units for `load` in `solve_network`.
- The value for `gdp` (USD) in 'build_shapes' seems too big.
- Some `mean_load` values (CPU usage percentage of the total running time) are grater than 100%.

**Comment by ekatef** [comment]
> Hi @ekatef , Thanks! Almost done! Indeed, installed capacity of generators is in MW, I think it is not necessary to explain CCGT and OCGT. I've also added the units for `lines_capacity` (MVA), `potential` (MW), and `avg_production_pu` (MWh), and incorporated links to PyPSA documentation explaining those units.
> 
> I still need to complete the following. Please let me know, if you have any hints:


Hi @javier-cp6, nice to see the progress :) Great idea to incorporate the links to the documentation!

The remaining questions are quite advanced ones. There are some ideas:

> * Units for `load` in `solve_network`.

I suspect "load" in this context can really mean load shedding. Could you please check if it's the case in fact?

> * The value for `gdp` (USD) in 'build_shapes' seems too big.

According to the [source article](https://doi.org/10.1038/sdata.2018.4) for GDP, the value correspond to "in constant 2011 international US dollars", while we are using 2020 to extract GDP. Inflation in Nigeria was about ~10% annually during 2011-2020 which seems to explain ~2.5 times difference we have. 

> * Some `mean_load` values (CPU usage percentage of the total running time) are grater than 100%.

Is it probably a consequence of using a multi-core processor?

**Comment by javier-cp6** [comment]
Hi @ekatef ,

Thanks for your explanations! I have finished updating the units and main descriptions for the stats in the notebook.  

This time,  I ran the `run_all_scenarios` rule, which automatically updates the configuration file for the Nigerias' test case and runs the `make_statistics` rule.  I think the PR is ready for review.

**Review by davide-f — COMMENTED** [review]
Hello @javier-cp6 !
Many thanks for the review and thanks for Katia for having followed you.
You did a great job and regarding the code I think we are ready to go.
I have only few minor comments:
- to align this notebook to the others, I'd recommend the parent folder to be named "pypsa-earth-project" instead the studio you used.
- regarding the description of how to use make statistics instead, I fear there is a bit of confusion: the rule make statistics can be used anytime, but ideally after a solve_all_networks. As such, the procedure may be: 1) run the tutorial (as you specified), 2) run 'snakemake -j1 make_statistics". This will generate the results/{scenario_code}stats.csv using the latest execution of the model: in the tutorial, the scenario code is null because the flag run->name code is null
- the rule make statistics is also automatically executed when using run_all_scenarios but in this case the stats.csv belong to each different scenario and they are placed into results/{scenarioname}/stats.csv

I think here we could have a description of the Sole make_statistics rule (2nd point) and maybe briefly explain that the function is iterated into run all scenarios to create many stats csv in every results/{scenario name}/stats.csv

After this, on my side, we are ready to go

**Comment by ekatef** [comment]
@javier-cp6 thanks for your amazing work, @davide-f thank you very much for the great review! Agree that we are close to finalise 🙂 

Some comments after playing a bit with this PR:
1. A generated stats table is a perfect way to obtain a big picture of the modeling. Really looking forward to have this PR merged! 
2. Davide's comments are crucial for usability: I needed some time to understand which folder is meant as `root/pypsa-earth` and failed to get `run_all_scenarios` work
3. Our discussion seems to be a good base to document both `make_statistics` and `run_all_scenarios`. [An issue](https://github.com/pypsa-meets-earth/pypsa-earth/issues/730) has been added to that

**Comment by javier-cp6** [comment]
Hi @ekatef , @davide-f ,

Thank you for your review and pointing out a potential confusion. I have updated the description so the `make_satistics` rule can be used anytime and explained the output format (`results/{run_name}/stats.csv`).  Additionally, I have added a note briefly explaining the `run_all_scenarios` rule., so both rules should be able to run to make the stats.

The given snippet for setting the parent folder is very useful indeed. Please, let me know if there are any additional tasks that need attention.

**Comment by davide-f** [comment]
Nice @javier-cp6 ! I slightly revise a text and ready to merge :)
Many thanks!

**Pull request merged**
