### PR TITLE
Add usage examples

### PR DESCRIPTION
**Pull request by ekatef**
Probably it could be helpful to add a handful usage examples.
Have transferred the notebooks which I have drafted as demonstration materials.

@pz-max, @davide-f, would be happy about your suggestions.

### CODE REVIEW

**Comment by davide-f** [comment]
Very nice description @ekatef :)

My comments are as follows:
1. what is the difference between the new notebooks and those in the main folder? I'd suggest to just fill the others.
2. In general, I'd suggest not to fill the notebooks at every commit but to fill them as a last step before merging. The commits lead to 10Mb of data that in case of changes will add up fast. I think we should try to reduce this and fill the notebooks only as a last step.

My suggestion would be to start a new PR with cleaned notebooks and fix the notebooks in the notebooks folder, without filling the data until the PR is about to be merged.
It would be nice to add a block like that also in the main documentation in the [notebooks folder of tutorial](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/doc/tutorial.rst), but this is related to another folder hence cannot be included here

**Comment by ekatef** [comment]
@davide-f, many thanks for the suggestions!

> My comments are as follows:
> 
> 1. what is the difference between the new notebooks and those in the main folder? I'd suggest to just fill the others.

The difference between the new notebooks and main-stream ones is in some little details only (like reproducibility comments added and some working fragments deleted). Probably, it could be better to introduce these changes into the main notebooks directly as the first step .

However, I feel it makes sense to distinguish between the tutorial notebooks and the working ones as they have clearly different purposes. Probably, we can try to use the notebooks from the main folder for introducing people into PyPSA workflow, collect feedback and then create a tutorial set tailored for tutorial use?

> 2. In general, I'd suggest not to fill the notebooks at every commit but to fill them as a last step before merging. The commits lead to 10Mb of data that in case of changes will add up fast. I think we should try to reduce this and fill the notebooks only as a last step.

> My suggestion would be to start a new PR with cleaned notebooks and fix the notebooks in the notebooks folder, without filling the data until the PR is about to be merged.

Thank you for the suggestion! Absolutely agree that it doesn't feel right to commit changes in the binaries...  :) No problem to re-open the PR after we'll agree the tutorials structure.

> It would be nice to add a block like that also in the main documentation in the [notebooks folder of tutorial](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/doc/tutorial.rst), but this is related to another folder hence cannot be included here

Absolutely agree that it'd be great to have links to the usage examples in the documentation and will be happy to do that. (Have I understood your idea properly? If not don't hesitate to correct me please :) )

**Comment by pz-max** [comment]
Short heads up. I like the distinction between tutorial focused notebooks and the ones that just dump out images, stats & brief explanations for large scale modelling exercises.

**Comment by pz-max** [comment]
@ekatef should this be merged? Please ping us when ready :100:

**Comment by ekatef** [comment]
@pz-max, not yet. Documentation fixes were the priority. 
Thank you for checking! Will be happy to notify you when this will be ready

**Comment by ekatef** [comment]
Sorry, had to fix some mess in my main branch... Will reopen once I'll align the content with new tutorial notebooks

**Pull request closed without merging**
