### PR TITLE
Tutorial network analysis

### PR DESCRIPTION
**Pull request by AnasAlgarei**
Adding a notebook for analysis of the pypsa-earth tutorial config. The resulting networks can be obtained from running the tutorial or by directly downloading them from the script in this notebook. The notebook also includes network analysis by the Network.statisitics feature. It also refers to the other notebooks in the documentation.
@pz-max @ekatef please check if you have time

### CODE REVIEW

**Comment by pz-max** [comment]
Hey @AnasAlgarei , looks good. Some possible improvements:
- [ ] Improvement. Delete outputs and compile that stuff from scratch with a kernel restart (I see some outputs marked by run 114 etc.)
- [ ] Improvement.. Having the `sets_path_to_root` & the progress download utility function here looks a bit ugly, just tell people at which path they should be located and what they should have installed in what structure to be able to execute everything. For instance, tell people to create a folder e.g. `mkdir pypsa-earth-project`, `cd pypsa-earth-project`, `git clone <pypsa-earth link> & git clone <documentation link> `. THIS IS THE FOLDER STRUCTURE WE ALSO NEED TO RUN ALL THE OTHER NOTEBOOKS ETC. VALIDATION.
- [ ] Improvement. Set the sys.path to import the set_path2_root and progress_retrieve function if needed. See here on how to do that: https://stackoverflow.com/a/50474562
- [ ] Improvement. You mention static and time-varying stuff. Where possible refer people to the PyPSA documentation such they can learn more about it. I would like to see these links somewhere. [PyPSA design](https://pypsa.readthedocs.io/en/latest/components.html#groups-of-components), [PyPSA components](https://pypsa.readthedocs.io/en/latest/components.html), example of to use the [PyPSA generator documentation](https://pypsa.readthedocs.io/en/latest/components.html#generator) such people learn how to access the variables given in the documentation.
- [ ] Fix. One of the cells says `home/anas/documentation` this won't work for everyone
- [ ] Fix. One of the cell mention 10 clusters/nodes while you use everywhere 6 nodes by default
- [ ] Fix. The solved Nigeria network map (current execution cell 79 shows about 50 buses... It should be 6?
- [ ] Check. Make sure that everything runs with one execution

**Comment by AnasAlgarei** [comment]
> Hey @AnasAlgarei , looks good. Some possible improvements:
> - [ ] Improvement. Delete outputs and compile that stuff from scratch with a kernel restart (I see some outputs marked by run 114 etc.)
> - [ ] Improvement.. Having the `sets_path_to_root` & the progress download utility function here looks a bit ugly, just tell people at which path they should be located and what they should have installed in what structure to be able to execute everything. For instance, tell people to create a folder e.g. `mkdir pypsa-earth-project`, `cd pypsa-earth-project`, `git clone <pypsa-earth link> & git clone <documentation link> `. THIS IS THE FOLDER STRUCTURE WE ALSO NEED TO RUN ALL THE OTHER NOTEBOOKS ETC. VALIDATION.
> - [ ] Improvement. Set the sys.path to import the set_path2_root and progress_retrieve function if needed. See here on how to do that: https://stackoverflow.com/a/50474562
> - [ ] Improvement. You mention static and time-varying stuff. Where possible refer people to the PyPSA documentation such they can learn more about it. I would like to see these links somewhere. [PyPSA design](https://pypsa.readthedocs.io/en/latest/components.html#groups-of-components), [PyPSA components](https://pypsa.readthedocs.io/en/latest/components.html), example of to use the [PyPSA generator documentation](https://pypsa.readthedocs.io/en/latest/components.html#generator) such people learn how to access the variables given in the documentation.
> - [ ] Fix. One of the cells says `home/anas/documentation` this won't work for everyone
> - [ ] Fix. One of the cell mention 10 clusters/nodes while you use everywhere 6 nodes by default
> - [ ] Fix. The solved Nigeria network map (current execution cell 79 shows about 50 buses... It should be 6?
> - [ ] Check. Make sure that everything runs with one execution

Hey @pz-max , many thanks for the review, very valuable notes, I'll fix it and commit again

**Comment by AnasAlgarei** [comment]
Hey @pz-max, I managed to do all the improvements/fixes, except for the n.plot() one, where it shows 50 buses instead of 6, I couldn't figure out what is causing it, I have 3 tutorial runs with the same result. Do you think it has something to do with the environment?

**Comment by ekatef** [comment]
@AnasAlgarei, great work! 
I have gone through your tutorial and was able to perfectly reproduce. The dispatch plot looks amazing. 

Two (rather minor) technical comments: 
1) does it probably make sense first to check if the requested file still exists before to load it?

2) is `socket import AF_X25` really needed? It looks like it's not in the pypsa-earth environment settings. Is is probably something system-specific? At least, I was able to run your code working perfectly well even without `socket` being installed.

Regarding number of buses on the picture produced `n.plot()`, it may look as there were some integrity issues with the underlying grid data. So, you have exactly six interconnected buses and a handful of isolated ones. Probably, it makes sense to play with `tol` or augmentation parameters. Or I do not get the point there? :)

**Comment by AnasAlgarei** [comment]
> @AnasAlgarei, great work! I have gone through your tutorial and was able to perfectly reproduce it. The dispatch plot looks amazing.
> 
> Two (rather minor) technical comments:
> 
> 1. does it probably make sense first to check if the requested file still exists before to load it?
> 2. is `socket import AF_X25` really needed? It looks like it's not in the pypsa-earth environment settings. Is is probably something system-specific? At least, I was able to run your code working perfectly well even without `socket` being installed.
> 
> Regarding number of buses on the picture produced `n.plot()`, it may look as there were some integrity issues with the underlying grid data. So, you have exactly six interconnected buses and a handful of isolated ones. Probably, it makes sense to play with `tol` or augmentation parameters. Or I do not get the point there? :)

Thanks for the review and comments @ekatef! 

1. That's really a good idea, I will try to implement it.
2. You're absolutely right! `socket` is not needed to generate the graph, I really don't know how it was added 😅 

I have been trying with the `n.plot()` issue with no luck until now, I am going to try and play with the `tol` you mentioned. Regardless of this, I think I still have some issues with my environment that I am trying to fix.

**Comment by davide-f** [comment]
Note. In the notebooks, there is the chdir("../../pypsa-earth") that is "unchedked": if it is run twice, it throws an error.
There is the need to enclose it in a if:
``` python
if not os.getcwd().endswith("pypsa-earth")
    os.chdir("../../pypsa-earth")
end
```

**Comment by AnasAlgarei** [comment]
Hey @davide-f @pz-max @ekatef, I updated the analysis notebook and hopefully it's good from all points except the buses issue. And I accidentally  made this last commit "Merge branch 'pypsa-meets-earth:main' into tut-net-analysis" and I don't know how to deal with it, can you just ignore it? 😅

**Comment by ekatef** [comment]
Hey @AnasAlgarei, with merging 'pypsa-meets-earth:main' into your branch you have updated your repository keeping it up-to date with the upstream. That will facilitate merging your PR and generally is good. So, don't worry please as you have done an absolutely right thing (see, e.g. https://stackoverflow.com/a/39822102/8465924).

By the way, probably it's a good idea to include our usual git workflow somewhere to the software hints part... :) [I usually look into my notes to do this updating magic]

**Comment by pz-max** [comment]
hey @AnasAlgarei, not sure if everything went right. Why you didn't compile the results at least once?
image

**Comment by AnasAlgarei** [comment]
> hey @AnasAlgarei, not sure if everything went right. Why you didn't compile the results at least once? We need to see the outputs
> image
> 

Hey @pz-max, so sorry I thought you wanted me to delete the outputs (from your first improvement suggestion) , now that I read again I understand, I'll do that and commit.

**Comment by AnasAlgarei** [comment]
Hey @pz-max, just committed with the outputs, I should report an issue that I had with the fresh environment when executing `n.plot()` (see figure). It's mainly related to the versions of `cartopy` and `matplotlib`, installing `matplotlib=3.5.2` solved it for me, but I am not sure if this will affect other packages. 
image

**Comment by pz-max** [comment]
@AnasAlgarei The notebook looks almost perfect. 

- [ ] We only need to explain what is `Load` in the carrier list here. As mentioned it is in fact `Demand Side Response` which might be clearer. Just explain it in text form when `load` as carrier appears the first time & maybe also the second time.

Regarding `matplotlib=3.5.2`, what was the previous version you installed?
- [ ] I think we would need to fix that in the environment.yaml in `pypsa-earth` OR integrate in the notebooks one line 
`pip install matplotlib=3.5.2` (maybe a quick and dirty approach which would be ok for now I guess. This line need to be briefly explained)

**Review by pz-max — CHANGES_REQUESTED** [review]
see comment

**Comment by AnasAlgarei** [comment]
> @AnasAlgarei The notebook looks almost perfect. 
> 
> - [ ] We only need to explain what is `Load` in the carrier list here. As mentioned it is in fact `Demand Side Response` which might be clearer. Just explain it in text form when `load` as carrier appears the first time & maybe also the second time.
> 
> Regarding `matplotlib=3.5.2`, what was the previous version you installed?
> - [ ] I think we would need to fix that in the environment.yaml in `pypsa-earth` OR integrate in the notebooks one line 
> `pip install matplotlib=3.5.2` (maybe a quick and dirty approach which would be ok for now I guess. This line need to be briefly explained)
> 

Thanks! this is because of your excellent suggestions. 
I'll add comments for the `load` and the line for `marplotlib` version. The version that was installed with the fresh environment is `3.6.0`, I changed it to `matplotlib=3.5.2` in environment.yaml and then created the environment again. I can make a PR with this for environment.yaml if you want? Or maybe we discuss this later.

**Comment by AnasAlgarei** [comment]
> Hey @pz-max, just committed with the outputs, I should report an issue that I had with the fresh environment when executing `n.plot()` (see figure). It's mainly related to the versions of `cartopy` and `matplotlib`, installing `matplotlib=3.5.2` solved it for me, but I am not sure if this will affect other packages. What do you think @ekatef, @davide-f? image

Hi @pz-max, I added a note for the load in the generators, and made a PR with `matplotlib=3.5.2` to the environment.yaml, which should fix the issue above, check: https://github.com/pypsa-meets-earth/pypsa-earth/pull/508. 
Hope everything is ready now!

**Comment by pz-max** [comment]
@AnasAlgarei ,, should have merged that on Friday ups. Congrats :D

**Comment by AnasAlgarei** [comment]
> @AnasAlgarei ,, should have merged that on Friday ups. Congrats :D

No worries, enjoy your weekend, thanks a lot 🙂

**Pull request merged**
