### PR TITLE
Add an overview notebook for analysis

### PR DESCRIPTION
**Pull request by doneachh**
A notebook with some quick plots to give a little bit of an overview of the current situation and the modelled scenario. #86

### CODE REVIEW

**Comment by doneachh** [comment]
@energyLS please review! :)

**Comment by doneachh** [comment]
@davide-f updated to lower_case tech_colors :)

**Review by davide-f — COMMENTED** [review]
Nice, this is a great notebook!
It would be nice to increase a bit the description of the cells to be easily understandable by new users.
Moreover, I'd recommend to keep lines short horizontally and you may split them vertically.
We can discuss about it, but the notebooks look nice :)

**Comment by doneachh** [comment]
Hi @davide-f ! :)
I've finalized the notebook, guess we can merge it. Automated the path settings and enabled color <-> nice_name matching.

**Comment by davide-f** [comment]
Great @doneachh !!! :D
I've added a minor comment and merging as Lint passes

**Review by davide-f — APPROVED** [review]

**Pull request merged**
