### PR TITLE
Include a section on hydro in the build_renewable_profile notebook

### PR DESCRIPTION
**Pull request by asolavi**
# Closes [#54 ]

This PR aims to create a section on hydro in the [build_renewable_profile.ipynb notebook](https://github.com/pypsa-meets-earth/documentation/blob/main/notebooks/build_renewable_profiles.ipynb), detailing the process made to create the hydro time series. Currently, built_renewable_profile.ipynb focuses on wind and solar.

Hydro modelling is done in three steps:

1. Preparation of hydro-potential data with atlite: ERA5 reanalysis dataset is used, runoff is being integrated across hydrobasins assuming some flow speed and put into cutout. This is done [here](https://github.com/PyPSA/atlite/blob/cc4ce153ad5885df164ac0706efc847090b22e15/atlite/hydro.py#L83-L106). More details in the methodology used by atlite can be found [here](https://atlite.readthedocs.io/en/latest/ref_api.html#atlite.Cutout.hydro).

2. The output of the time series obtained in step 1 (cutout hydro potential) is normalized in pypsa-earth using the normalization procedure described [here](https://github.com/pypsa-meets-earth/pypsa-earth/blob/186d2d23f6fad955e8a2f253e08c8b129af0e423/scripts/build_renewable_profiles.py#L315C61-L315C61). This is done to match country statistics. The result is stored in `resources/renewable_profiles/profile_hydro.nc`.

3. Attach_hydro in add_electricity, as described [here](https://github.com/pypsa-meets-earth/pypsa-earth/blob/186d2d23f6fad955e8a2f253e08c8b129af0e423/scripts/add_electricity.py#L443). Specifies how the different hydro types (runoff river (`ror`), hydro dams (`hydro`), and pumped storage (`PHS`) are added to the network in `add_electricity`.

## Checklist

- [X] I consent to the release of this PR's code under the GPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [x] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by asolavi** [comment]
One question for the experts:

1. Are inflows from the xarray in `resources/renewable_profiles/profile_hydro.nc` in MW or in a "water unit" (e.g., depth of water in meters if it were spread over the corresponding region/cell)?

**Comment by ekatef** [comment]
> One question for the experts:
> 
> 1. Are inflows from the xarray in `resources/renewable_profiles/profile_hydro.nc` in MW or in a "water unit" (e.g., depth of water in meters if it were spread over the corresponding region/cell)?

Hello @asolavi! Fantastic work 😄 

Great to have well-elaborated explanation of details of hydro calculations. To me, our hydro calculations still have a bit of mystery :)

According to the docstring, the hydro profiles inflows are in MW:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/990132f90dba64147309136a6a38905afe0c45fd/scripts/build_renewable_profiles.py#L101-L102

That simplifies work with hydro generation, e.g. we need only account for GWh -> W transformation when doing normalisation of hydro:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/990132f90dba64147309136a6a38905afe0c45fd/scripts/build_renewable_profiles.py#L271-L278

https://github.com/pypsa-meets-earth/pypsa-earth/blob/990132f90dba64147309136a6a38905afe0c45fd/scripts/build_renewable_profiles.py#L417

Although, I can't say that unit transformation is absolutely evident for me from `atlite` source code, where [shift_and_aggregate_runoff_for_plants()](https://github.com/PyPSA/atlite/blob/549d0fdf22925e06ac3f726e801f215d993671dc/atlite/hydro.py#L83 function) is used to translate water depth per cell area into MW (https://github.com/PyPSA/atlite/blob/549d0fdf22925e06ac3f726e801f215d993671dc/atlite/hydro.py#L83 function)

**Comment by asolavi** [comment]
> 

Thank you @ekatef. I've been further looking into this and, from my understanding, it seems that:

1.  `cutouts/{cutout_name}-2013-era5nc` has the surface runoff in depth of water in meters if it were spread over the corresponding region/cell.

2. As you mentioned above, the docstring in build_renewable_profiles.py suggests that inflows are in MW already.

3. The file `data/eia_hydro_annual_generation.csv` is expressed in billions kWh per year. This is one of the possibile sources to do the normalization.

I also don't see exactly where the transformation from depth of water per area to an energy unit happens. I suspect that it takes place indirectly in the normalization. This is because the normalization makes the total hydro generation equal to the total generation of an energy metric (MWh or another one), while preserving the local distribution across several regions from the ERA5 dataset.

What do you think? Is this reasonable?

**Comment by ekatef** [comment]
> Thank you @ekatef. I've been further looking into this and, from my understanding, it seems that:
> 
> 
> 
> 1.  `cutouts/{cutout_name}-2013-era5.nc` has the surface runoff in depth of water in meters if it were spread over the corresponding region/cell.
> 
> 
> 
> 2. As you mentioned above, the docstring in build_renewable_profiles.py suggests that inflows are in MW already.
> 
> 
> 
> 3. The file `data/eia_hydro_annual_generation.csv` is expressed in billions kWh per year. This is one of the possibile sources to do the normalization.
> 
> 
> 
> I also don't see exactly where the transformation from depth of water per area to an energy unit happens. I suspect that it takes place indirectly in the normalization. This is because the normalization makes the total hydro generation equal to the total generation of an energy metric (MWh or another one), while preserving the local distribution across several regions from the ERA5 dataset.
> 
> 
> 
> What do you think? Is this reasonable?

I think you may be absolutely right. It looks like we silently assume during normalisation that hydropower generation linearly depends on runoff, and scaling is used both for value and unit transformation. If that is the case, probably the docstring can be a bit clarified in part where inflows are introduced.

I'd suggest to discuss it during today's meeting, as it feels like a major question.

**Comment by asolavi** [comment]
Hi @ekatef and @tacwebservices,

as per the discussion yesterday, I've improved the description on the units used. I think it is now ready to merge :). Let me know if you agree, or if there is anything that should be changed.

**Comment by ekatef** [comment]
Hey @asolavi and @tacwebservices! Great and very helpful work 🙂 

A couple of minor comments (sorry, can't paste it into the code, as git complains on big diff size).
* `Add hydro types`: not sure it it's clear, could it be probably improved.
* "It then rescales the inflows obtained in step 1 so that the totals are the same,...":  seems that would be nice to clarify that the same implies comparison against the statistic data?

Otherwise, looks perfect to me 🙂 
@davide-f would you have any comments?

**Review by davide-f — COMMENTED** [review]
Hello @asolavi and @tacwebservices ! :D
Great job as always! You are amazing in documentation!!!

The PR is in good state,I'd have few comments:
- in the section "What Happens behind the Scenes of Hydro Modelling?" it may be better to disentangle the point 1 on data into two blocks: (1) the raw data downloaded from a server (e.g. era5 but others may apply) and stored into the cutout and (2) the intermediate processing of the hydro function of atlite. I think it may be better to clarify with (1) the starting point of the raw data, hence era5 or other equivalent data source, and (2) the postprocessing on those data internally performed by atlite.
- there are few typo (e.g. "obtention" in "What Happens behind the Scenes of Hydro Modelling?"), but maybe I found the only one...
The rest is perfect :)

**Comment by davide-f** [comment]
Hello @asolavi and @tacwebservices ! :D
Great job as always! You are amazing in documentation!!!

The PR is in good state,I'd have few comments:
- in the section "What Happens behind the Scenes of Hydro Modelling?" it may be better to disentangle the point 1 on data into two blocks: (1) the raw data downloaded from a server (e.g. era5 but others may apply) and stored into the cutout and (2) the intermediate processing of the hydro function of atlite. I think it may be better to clarify with (1) the starting point of the raw data, hence era5 or other equivalent data source, and (2) the postprocessing on those data internally performed by atlite.
- there are few typo (e.g. "obtention" in "What Happens behind the Scenes of Hydro Modelling?"), but maybe I found the only one...

The rest is perfect :) Great job!

**Comment by asolavi** [comment]
Thank you for your detailed feedback @ekatef and @davide-f. I believe it has now been implemented and it is ready to merge :). Let me know what you think

**Comment by davide-f** [comment]
Looks good to me :) I Katia agrees we can merge.
Amazing! :D

**Review by davide-f — APPROVED** [review]

**Comment by davide-f** [comment]
Merged, fantastic job! :D

**Comment by asolavi** [comment]
Great, thank you for your help and feedback @davide-f @ekatef

**Pull request merged**
