### PR TITLE
CSP power generation into Current Notebooks

### PR DESCRIPTION
**Pull request by GbotemiB**
This PR includes integration of the CSP technology into the `build_renewable_profiles` and the `landuse_availabilty` notebooks.

### CODE REVIEW

**Comment by GbotemiB** [comment]
While I reran the notebooks, some of the analysis plots changed. I don't know if that's ok.

**Comment by ekatef** [comment]
> While I reran the notebooks, some of the analysis plots changed. I don't know if that's ok.

Could you please elaborate a bit? 🙂 Notebooks are not exactly friendly in terms of reproducibility, that is always best to restart, when generating the results.

**Comment by GbotemiB** [comment]
> My general impression is that the results are quite insightful. In particular, I haven't expected that CSP resources will be so close to PV ones.
> 
> To have some cross-validation: [this resource](https://solargis.com/maps-and-gis-data/download/world) which can be convenient to inter-compare PV vs CSP. Note that the colorbare scale is different for both resources, which make it difficult to compare them. My general impression is that spatial patterns are pretty much the same in both cases. Values seem to be also in the same range, with CSP potential being only slightly lower.
> 
> @GbotemiB could you please post results of the quantitative comparison you have done for solar and csp?

This is the result obtained using `build_renewable_profile` notebook
image

Also, the time series output for solar and csp looks similar
image

image

**Comment by GbotemiB** [comment]
> > While I reran the notebooks, some of the analysis plots changed. I don't know if that's ok.
> 
> Could you please elaborate a bit? 🙂 Notebooks are not exactly friendly in terms of reproducibility, that is always best to restart, when generating the results.

Discussing the difference in results, Here is the plot from `landuse_availability` notebook
This is from the main notebook
image

This is from reruning the notebook
image

Considering the technical results too
Here are the results from the initial notebook
image

While looking at the results obtained from rerunning the notebook
image

**Comment by ekatef** [comment]
Hello @GbotemiB!

A great addition to the documentation 😄 

A couple of comments:
1. It looks like CSP has pretty same landuse availability as PV. At least, that seems to be the case in the current implementation, for which we do not account for the slope effect. So, not sure it makes sense to include CSP into the final version of the landuse-availability notebook. [Thogh, that is definitely a great idea to have both plots on the testing stage]
2. Regarding the renewable profiles, I think we need to replace `csp["p_nom_max"] * csp["profile"]` with the generator output, as you have done when analysing the dispatch plot.
3. A technical point: `"solar-power-profile.pdf"` should be replaced with `"csp-power-profile.pdf"` under `plt.savefig`.

**Comment by GbotemiB** [comment]
> Hello @GbotemiB!
> 
> A great addition to the documentation 😄
> 
> A couple of comments:
> 
> 1. It looks like CSP has pretty same landuse availability as PV. At least, that seems to be the case in the current implementation, for which we do not account for the slope effect. So, not sure it makes sense to include CSP into the final version of the landuse-availability notebook. [Thogh, that is definitely a great idea to have both plots on the testing stage]
> 2. Regarding the renewable profiles, I think we need to replace `csp["p_nom_max"] * csp["profile"]` with the generator output, as you have done when analysing the dispatch plot.
> 3. A technical point: `"solar-power-profile.pdf"` should be replaced with `"csp-power-profile.pdf"` under `plt.savefig`.

Thanks @ekatef for the review.

Regarding 2, the generator output that was used for analysing the dispatch plot was done from the network profile. I am not sure if we can achieve the same with just the renewable_profile object file. Also, that would also translate to changing the formula for wind and solar pv too.

**Comment by ekatef** [comment]
> 3\. sp-power-profile

Hello @GbotemiB, 

As a second thought, it's also highly meaningful information that CSP has the same land availability as PV for the considered case. Apart of that, the notebook can also be used to investigate the areas where that is not the case. So, I'd leave the landuse plot as is. 

Agree on the point regarding the generation output for CSP. Let's just fix the axis name changing `csp power output` into something like `CSP input solar power` to highlight that it's not yet the electric power. After adding this fix and changing the name of the output file (point 3), I think the notebook is ready to merge 🙂

**Comment by GbotemiB** [comment]
@ekatef Thanks for the review. I have implemented the suggestions. I have also reverted the landuse notebook to the original version. The CI is also successful.

**Comment by ekatef** [comment]
Merged @GbotemiB 🎉 🎉 🎉 
Thanks a lot for the great contribution! 😄

**Comment by GbotemiB** [comment]
@ekatef Thanks for the amazing support.

**Pull request merged**
